env:
  global:
    - COMPOSER_DISABLE_XDEBUG_WARN="1"

matrix:
  include:
    - os: linux
      language: php
      php: 5.3
      dist: precise
      env:
        PHPCS_VER="^2"

    - os: linux
      language: php
      php: 5.4
      env:
        PHPCS_VER="^3"

    - os: linux
      language: php
      php: 5.5
      env:
        PHPCS_VER="^3"

    - os: linux
      language: php
      php: 5.6
      env:
        PHPCS_VER="^3"

    - os: linux
      language: php
      php: 7.0
      env:
        PHPCS_VER="^3"

    - os: linux
      language: php
      php: 7.1
      env:
        PHPCS_VER="^3"

    - os: linux
      language: php
      php: 7.2
      env:
        PHPCS_VER="^3"


install:
  - composer install
  - export PATH="$PATH:$HOME/.composer/vendor/bin"
  - composer global require "squizlabs/php_codesniffer $PHPCS_VER"

before_script:
  - if find . -name "*.php" ! -path "./vendor/*" -print0 | xargs -0 -n 1 -P 8 php -l | grep -v "No syntax errors detected"; then exit 1; fi

script: true
